apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\badal\Documents\Futurense US Pathway\Pipeline\Main\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "9093"
    port: 9093
    targetPort: 9093
  selector:
    io.kompose.service: kafka
status:
  loadBalancer: {}
